server:
  port: 8002
spring:
  application:
    name: eureka
eureka:
  instance:
    hostname: eureka8002.com
    prefer-ip-address: false
  client:
#    registerWithEureka: false
#    fetchRegistry: false
    serviceUrl:
      defaultZone: http://eureka8001.com:8001/eureka/,http://eureka8003.com:8003/eureka/