server:
  port: 8003
spring:
  application:
    name: eureka
eureka:
  instance:
    hostname: eureka8003.com
    prefer-ip-address: false
  client:
#    registerWithEureka: false
#    fetchRegistry: false
    serviceUrl:
      defaultZone: http://eureka8001.com:8001/eureka/,http://eureka8002.com:8002/eureka/
